version: '3.8'

services:
  mtprotoproxy:
    build: .
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config.py:/home/tgproxy/config.py
      - ./mtprotoproxy.py:/home/tgproxy/mtprotoproxy.py
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    mem_limit: 512m  # có thể bật lại nếu muốn
    user: root  # ⚠️ cần thiết nếu gặp lỗi "operation not permitted"
